num_worker: 0
work_dir: ./work_dir/x_sub/bone_com2_no_body

# feeder
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: D:/minuk_folder/CTR-GCN-main/CTR-GCN-main/data/ntu/NTU60_CS_no_body.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  bone: True

test_feeder_args:
  data_path: D:/minuk_folder/CTR-GCN-main/CTR-GCN-main/data/ntu/NTU60_CS_no_body.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  bone: True
  debug: False

# model
model: model.HDGCN.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d_hierarchy.Graph
  graph_args:
    labeling_mode: 'spatial'
    CoM: 2

#optim
weight_decay: 0.0004
base_lr: 0.1
warm_up_epoch: 5

# training
device: [0]
batch_size: 64
test_batch_size: 64
num_epoch: 90
nesterov: True
